import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar/Navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			style={{scrollBehavior: 'smooth'}}
			className='overflow-x-hidden w-full'
		>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
